version: "3"
services:

  app:
    image: "jetbrains/teamcity-server:2018.2.3-linux"
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
#    ports:
#      - "8111:8111"
    expose:
      - 8111
    volumes:
      - "data:/data/teamcity_server/datadir"
      - "logs:/opt/teamcity/logs"
    labels:
      - "traefik.backend=teamcity_app"
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
    networks:
      - "teamcity"
    restart: always

  agent:
    image: "jetbrains/teamcity-agent:2018.2.3-linux"
    restart: always
    networks:
      - "teamcity"
    labels:
      - "traefik.backend=teamcity_agent"
    volumes:
      - "agent_config:/data/teamcity_agent/conf"
      - "docker_volumes:/var/lib/docker"
    environment:
      AGENT_NAME: "teamcity_agent"
      DOCKER_IN_DOCKER: "start"
      SERVER_URL: "app:8111"
    privileged: true

  db:
    image: "postgres:10.7"
    restart: always
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - "pg_backup:/backup/"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    networks:
      - "teamcity"
    labels:
      - "traefik.backend=teamcity_db"
    command: [
      "postgres",
      "-c", "timezone=${TIMEZONE}",
      "-c", "log_timezone=${TIMEZONE}"
    ]

volumes:
  pg_data:
  pg_backup:
  data:
  logs:
  agent_config:
  docker_volumes:

networks:
  teamcity:
    external:
      name: "${NETWORK}"
