version: '3'
services:

  teamcity:
    image: "jetbrains/teamcity-server:latest"
    container_name: "teamcity"
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
    expose:
      - "8111"
    volumes:
      - "data:/data/teamcity_server/datadir"
      - "logs:/opt/teamcity/logs"
    restart: always
    depends_on:
      - db

  db:
    image: "postgres:10.4"
    container_name: "teamcity-db"
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "root"
      POSTGRES_DB: "teamcity"
    expose:
      - "5432"

  web:
    image: "mcsim/openresty:base"
    container_name: "teamcity-web"
    restart: always
    volumes:
      - "./conf.d:/etc/nginx/conf.d/templates"
    expose:
      - "80"
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
    depends_on:
      - teamcity
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
    command: /bin/bash -c "envsubst '$${DOMAIN_NAME}' < /etc/nginx/conf.d/templates/teamcity.template > /etc/nginx/conf.d/default.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"

volumes:
  data:
    driver: local
  logs:
    driver: local
  db_data:
    driver: local
networks:
  default:
    external:
      name: teamcity